-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT book.ID AS ENTITY_ID, book.NAME AS ENTITY_NAME,
       book.REGION, book.CATEGORY, book.RISK_TIER, book.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.CLAIM_COUNT) AS CLAIM_COUNT,
       SUM(observation.CLAIMS_PAID_USD) AS CLAIMS_PAID_USD,
       SUM(observation.EARNED_PREMIUM_USD) AS EARNED_PREMIUM_USD,
       SUM(observation.REFERRAL_COUNT) AS REFERRAL_COUNT,
       SUM(observation.CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(observation.CLAIMS_DENIED) AS DENIED_COUNT,
       SUM(observation.AUDIT_DUE) AS AUDIT_DUE,
       SUM(observation.AUDIT_COMPLETED) AS AUDIT_COMPLETED,
       100.0 * SUM(observation.CLAIMS_PAID_USD) / NULLIF(SUM(observation.EARNED_PREMIUM_USD), 0) AS LOSS_RATIO_PCT,
       100.0 * SUM(observation.CONFIRMED_COUNT) / NULLIF(SUM(observation.REFERRAL_COUNT), 0) AS REFERRAL_PRECISION_PCT,
       100.0 * SUM(observation.AUDIT_COMPLETED) / NULLIF(SUM(observation.AUDIT_DUE), 0) AS AUDIT_COMPLIANCE_PCT,
       AVG(observation.DOC_MISMATCH_PCT) AS AVG_DOC_MISMATCH_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.BOOK_DAILY observation
JOIN RAW.POLICY_BOOKS book ON book.ID = observation.ENTITY_ID
GROUP BY book.ID, book.NAME, book.REGION, book.CATEGORY, book.RISK_TIER, book.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(CLAIM_COUNT) AS CLAIM_COUNT, SUM(CLAIMS_PAID_USD) AS CLAIMS_PAID_USD,
       SUM(EARNED_PREMIUM_USD) AS EARNED_PREMIUM_USD,
       SUM(REFERRAL_COUNT) AS REFERRAL_COUNT, SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       100.0 * SUM(CLAIMS_PAID_USD) / NULLIF(SUM(EARNED_PREMIUM_USD), 0) AS LOSS_RATIO_PCT
FROM RAW.BOOK_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.INDICATOR_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT FRAUD_INDICATOR, SUM(REFERRAL_COUNT) AS REFERRAL_COUNT,
       SUM(CONFIRMED_COUNT) AS CONFIRMED_COUNT,
       SUM(CLAIMS_DENIED) AS DENIED_COUNT,
       SUM(CLAIMS_PAID_USD) AS REFERRED_DAY_PAID_USD,
       100.0 * SUM(CONFIRMED_COUNT) / NULLIF(SUM(REFERRAL_COUNT), 0) AS REFERRAL_PRECISION_PCT
FROM RAW.BOOK_DAILY
WHERE REFERRAL_COUNT > 0
GROUP BY FRAUD_INDICATOR;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(CLAIM_COUNT) AS CLAIMS, SUM(CLAIMS_PAID_USD) AS PAID,
         SUM(EARNED_PREMIUM_USD) AS PREMIUM,
         SUM(REFERRAL_COUNT) AS REFERRALS, SUM(CONFIRMED_COUNT) AS CONFIRMED,
         SUM(CLAIMS_DENIED) AS DENIED,
         SUM(AUDIT_DUE) AS AUDIT_DUE, SUM(AUDIT_COMPLETED) AS AUDIT_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.BOOK_DAILY
), portfolio AS (SELECT COUNT(*) AS BOOK_COUNT FROM RAW.POLICY_BOOKS),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.CLAIM_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Loss Ratio' AS TITLE,
         100.0 * PAID / NULLIF(PREMIUM, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Claims Filed', CLAIMS, '' FROM observations
  UNION ALL SELECT 3, 'Claims Paid (USD M)', PAID / 1e6, '' FROM observations
  UNION ALL SELECT 4, 'SIU Referrals', REFERRALS, '' FROM observations
  UNION ALL SELECT 5, 'Confirmed Fraud', CONFIRMED, '' FROM observations
  UNION ALL SELECT 6, 'Referral Precision', 100.0 * CONFIRMED / NULLIF(REFERRALS, 0), '%' FROM observations
  UNION ALL SELECT 7, 'Fraudulent Claims Denied', DENIED, '' FROM observations
  UNION ALL SELECT 8, 'Claims File Audit Compliance', 100.0 * AUDIT_COMPLETED / NULLIF(AUDIT_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Policy Books Monitored', BOOK_COUNT, '' FROM portfolio
  UNION ALL SELECT 10, 'Claim Document Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Claim Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.INDICATOR_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
