-- Claims fraud risk scoring and SIU referral forecast over the synthetic snapshot.
-- Predicts P(confirmed fraudulent claim in the next 7 days) per policy book and
-- reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.FRAUD_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, b.CATEGORY, b.RISK_TIER, b.AVG_TENURE_YEARS,
       r.DOC_MISMATCH_PCT, r.EARLY_CLAIM_PCT,
       AVG(r.DOC_MISMATCH_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS DOC_MISMATCH_7D,
       SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS CONFIRMED_30D,
       IFF(SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'FRAUD', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.BOOK_DAILY r JOIN RAW.POLICY_BOOKS b ON b.ID = r.ENTITY_ID
-- Catastrophe surges are market-wide, not book-driven, so they are excluded from training.
WHERE r.FRAUD_INDICATOR <> 'Catastrophe claim surge';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.FRAUD_TRAIN AS
SELECT CATEGORY, RISK_TIER, AVG_TENURE_YEARS, DOC_MISMATCH_PCT, EARLY_CLAIM_PCT, DOC_MISMATCH_7D, CONFIRMED_30D, LABEL
FROM ML.FRAUD_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.FRAUD_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, RISK_TIER, AVG_TENURE_YEARS, DOC_MISMATCH_PCT, EARLY_CLAIM_PCT, DOC_MISMATCH_7D, CONFIRMED_30D, LABEL
FROM ML.FRAUD_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.FRAUD_RISK_MODEL(
  INPUT_DATA => TABLE(ML.FRAUD_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.FRAUD_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.FRAUD_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'AVG_TENURE_YEARS', AVG_TENURE_YEARS,
           'DOC_MISMATCH_PCT', DOC_MISMATCH_PCT, 'EARLY_CLAIM_PCT', EARLY_CLAIM_PCT,
           'DOC_MISMATCH_7D', DOC_MISMATCH_7D, 'CONFIRMED_30D', CONFIRMED_30D)):probability:FRAUD::FLOAT AS P
  FROM ML.FRAUD_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'FRAUD', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'FRAUD', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'FRAUD', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'FRAUD', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per book (label unknown, so excluded from features).
CREATE TABLE ML.FRAUD_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.FRAUD_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.FRAUD_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'AVG_TENURE_YEARS', AVG_TENURE_YEARS,
           'DOC_MISMATCH_PCT', DOC_MISMATCH_PCT, 'EARLY_CLAIM_PCT', EARLY_CLAIM_PCT,
           'DOC_MISMATCH_7D', DOC_MISMATCH_7D, 'CONFIRMED_30D', CONFIRMED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:FRAUD::FLOAT, 4) AS FRAUD_PROB_7D,
       CASE WHEN P:probability:FRAUD::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:FRAUD::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Portfolio-wide daily claims forecast (14 days), for claims-handler staffing.
CREATE VIEW ML.DAILY_CLAIMS AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(CLAIM_COUNT)::FLOAT AS CLAIM_COUNT
FROM RAW.BOOK_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.CLAIMS_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_CLAIMS),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'CLAIM_COUNT'
);

CREATE TABLE ML.CLAIMS_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS CLAIM_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.CLAIMS_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
